# build site settings
remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme
gem "github-pages", group: jekyll_plugins
title: Bells Beltmaking
description: Finest handcrafted belts in Dallas, Texas.
show_downloads: true 
